---
deployment:
  tasks:
    - export DEPLOYPATH=/home/diso2055/sites/lesecolesalbaraime/
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R storage $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp artisan $DEPLOYPATH
    - cd $DEPLOYPATH && php artisan migrate --force
    - cd $DEPLOYPATH && php artisan config:cache
    - cd $DEPLOYPATH && php artisan route:cache
    - cd $DEPLOYPATH && php artisan view:cache